POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1mb3dsZXIiLCJpZCI6IjVmMDUwNjhlMWJhYWIwMGZjN2U3ODgyYyIsImlhdCI6MTU5NDIzMDg4OX0.1S508mtcxY1TJdAHXb7Uanl0My1hzWv66VMtnN1kPzk

{
    "title": "Introduction to Testing IV",
    "name": "Martin Fowler the 4th",
    "url": "https://www.google.com",
    "likes": 18
}